vim.keymap.set('n', '<leader>pv', '<cmd>e .<cr>', { desc = "Open current working directory (pwd)" })
vim.keymap.set('n','<leader>pV','<cmd>e %:p:h<cr>', { desc = "Open parent directory of file" })
vim.keymap.set('n','<leader>r',function()vim.diagnostic.jump({count=(vim.v.count ==0 and 1 or vim.v.count), float=true})end, {desc = "Jump to next diagnostic"})
vim.keymap.set('n','<leader>R',function()vim.diagnostic.jump({count=(vim.v.count ==0 and -1 or vim.v.count), float=true})end ,{desc = "Jump to previous diagnostic"})
vim.keymap.set('n','<leader>ff','<cmd>FzfLua files<cr>' ,{desc = "FZF find files"})
vim.keymap.set('n','<leader>fg','<cmd>FzfLua grep<cr>' ,{desc = "FZF grep"})
vim.keymap.set('n','<leader>fo','<cmd>FzfLua<cr>' ,{desc = "FZF open menu"})
vim.keymap.set('n','<leader>fr','<cmd>FzfLua resume<cr>' ,{desc = "FZF resume previous"})
vim.keymap.set('n','<leader>frr','<cmd>FzfLua lsp_references<cr>' ,{desc = "FZF lsp reference"})
