vim.keymap.set('n','<leader>pv','<cmd>e .<cr>')
vim.keymap.set('n','<leader>pV','<cmd>e %:p:h<cr>')
vim.keymap.set('n','<leader>r',vim.diagnostic.goto_next)
vim.keymap.set('n','<leader>R',vim.diagnostic.goto_prev)
vim.keymap.set('n','<leader>ff','<cmd>FzfLua files<cr>')
vim.keymap.set('n','<leader>fg','<cmd>FzfLua grep<cr>')
