vim.keymap.set('n', '<leader>pv', '<cmd>e .<cr>', { desc = "Open current working directory (pwd)" })
vim.keymap.set('n', '<leader>pV', '<cmd>e %:p:h<cr>', { desc = "Open parent directory of file" })
vim.keymap.set('n', '<leader>r',
    function() vim.diagnostic.jump({ count = (vim.v.count == 0 and 1 or vim.v.count), float = true }) end,
    { desc = "Jump to next diagnostic" })
vim.keymap.set('n', '<leader>R',
    function() vim.diagnostic.jump({ count = (vim.v.count == 0 and -1 or vim.v.count), float = true }) end,
    { desc = "Jump to previous diagnostic" })
vim.keymap.set('n', '<leader>ff', '<cmd>FzfLua files<cr>', { desc = "FZF find files" })
vim.keymap.set('n', '<leader>fg', '<cmd>FzfLua grep<cr>', { desc = "FZF grep" })
vim.keymap.set('n', '<leader>fo', '<cmd>FzfLua<cr>', { desc = "FZF open menu" })
vim.keymap.set('n', '<leader>fr', '<cmd>FzfLua resume<cr>', { desc = "FZF resume previous" })
vim.keymap.set('n', '<leader>frr', '<cmd>FzfLua lsp_references<cr>', { desc = "FZF lsp reference" })
vim.keymap.set('n', '<leader>fb', '<cmd>FzfLua buffers<cr>', { desc = "FZF buffers" })
-- DEBUGGER KEYMAPS
vim.keymap.set('n', '<F5>', function() require('dap').continue() end, { desc = "Debugger run" })
vim.keymap.set('n', '<F10>', function() require('dap').step_over() end, { desc = "Debugger step over" })
vim.keymap.set('n', '<F11>', function() require('dap').step_into() end, { desc = "Debugger step into" })
vim.keymap.set('n', '<F12>', function() require('dap').step_out() end, { desc = "Debugger step out" })
vim.keymap.set('n', '<Leader>b', function() require('dap').toggle_breakpoint() end, { desc = "Toggle Breakpoint" })
vim.keymap.set('n', '<Leader>B', function() require('dap').set_breakpoint() end, { desc = "Set Breakpoint" })
vim.keymap.set('n', '<Leader>lp',
    function() require('dap').set_breakpoint(nil, nil, vim.fn.input('Log point message: ')) end,
    { desc = "Set Log Breakpoint" })
vim.keymap.set('n', '<Leader>dr', function() require('dap').repl.open() end, { desc = "DAP open REPL console" })
vim.keymap.set('n', '<Leader>dl', function() require('dap').run_last() end, { desc = "DAP run last" })
vim.keymap.set({ 'n', 'v' }, '<Leader>dh', function()
    require('dap.ui.widgets').hover()
end, { desc = "DAP hover" })
vim.keymap.set({ 'n', 'v' }, '<Leader>dp', function()
    require('dap.ui.widgets').preview()
end, { desc = "DAP preview" })
vim.keymap.set('n', '<Leader>df', function()
    --local widgets = require('dap.ui.widgets')
    --widgets.centered_float(widgets.frames)
    local fzf = require('fzf-lua')
    fzf.dap_frames()
end, { desc = "DAP show frames (FZF)" })
vim.keymap.set('n', '<Leader>ds', function()
    local widgets = require('dap.ui.widgets')
    widgets.centered_float(widgets.scopes)
end, { desc = "DAP show scopes" })
